version: "3.9"
services:
    authservice:
        image: microtex.azurecr.io/authservice:v1.0.3
        ports:
            - "3002:3002"
        restart: on-failure:5
        # deploy:
        #     restart_policy:
        #         condition: on-failure
        #         max_attempts: 3
    citymaster:
        image: microtex.azurecr.io/citymaster:v1.0.2
        ports:
            - "3001:3001"
        # deploy:
        #     restart_policy:
        #         condition: on-failure
        #         max_attempts: 3
    accountmaster:
        image: microtex.azurecr.io/accountmaster:v1.1.3
        ports:
            - "3003:3003"
        # deploy:
        #     restart_policy:
        #         condition: on-failure
        #         max_attempts: 3
    designmaster:
        image: microtex.azurecr.io/designmaster:v1.0.2
        ports:
            - "3004:3004"
        # deploy:
        #     restart_policy:
        #         condition: on-failure
        #         max_attempts: 3
    userservice:
        image: microtex.azurecr.io/userservice:v1.1.7
        ports:
            - "3005:3005"
        restart: on-failure:5
        # deploy:
        #     restart_policy:
        #         condition: on-failure
        #         max_attempts: 3
    transactionservice:
        image: microtex.azurecr.io/transactionservice:v1.1.3
        ports:
            - "3007:3007"
        # deploy:
        # restart_policy:
        #     condition: on-failure
        #     max_attempts: 3
    app:
        image: microtex.azurecr.io/app:v1.3
        ports:
            - "80:80"
        # deploy:
        # restart_policy:
        #     condition: on-failure
        #     max_attempts: 3
