CREATE TABLE `SALES_ORDER` (
  `BILL_NO` int(11) NOT NULL,
  `CNAME` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
  `ORDER_DATE` date DEFAULT NULL
);

ALTER TABLE `SALES_ORDER`
  ADD PRIMARY KEY (`BILL_NO`);
  
CREATE TABLE `SALES_ORDER_DETAILS` (
  `BILL_NO` int(11) DEFAULT NULL,
  `NAME` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
  `QTY` int(11) DEFAULT NULL,
  `RATE` int(11) DEFAULT NULL,
  `TYPE` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL
);